### ISSUE TITLE
（法務？）PullReqを受け入れる時に、商用サポート付きライセンスをどう扱うか

### ISSUE THREAD

**Issue by AknEp** [AknEp/lily#13]
PullReqを受け入れる場合、ここに明記してあるMITの元で使う分には問題ないと思うのだけれど、
Lilyは今後、同一のコードベースで（商用ゲームに適した機能拡充などをすることを想定しつつ）商用ライセンスとして展開する可能性がある。
（※必ずやるということではなく、その展開も可能な状態にしておきたい、ということです。）

確か、ソフトイーサさんがVPNをOSSにするときに、同様の事を気にしていた気がするので、ちょっと調べてみる。

**Comment by AknEp** [comment]
http://www.softether.org/5-download/src/9.patch

ソフトイーサさんでは、極めて明確に書いてある。
以下に引用する（このまま使うわけではないですよ！ この文章にも著作権があるので！）

http://www.softether.org/5-download/src/9.patch

```
Contribution option (1): Allowing us to apply the same patch into PacketiX VPN. (Default)

It means that you grant us to re-use your patch for PacketiX VPN (and its descendants).
Since PacketiX VPN is a proprietary product, your patch on PacketiX VPN will be treated as non-GPL code. SoftEther Corporation (PacketiX VPN's manufacturer) may use your patch to enrich the product quality or functionality.
```

SoftEther VPN のリポジトリを見ると、PRひとつひとつに、コントリビューションのオプションを聞いているのが分かる。


ここまで検討して思ったけれど、SoftEtherさんはGPLだからややこしい形式になっているのであって、
「パッチにもMITライセンスを適用する」事を明示的にするのであれば、そもそもパッチを商用利用しても問題ないのでは…？と気づいた。

勘違いじゃなければ、後ほどクローズする。

**Comment by AknEp** [comment]
RHELやMySQLもOSSかつ商用ライセンスを持つものだけれど、どれもGPL。

MITにした時点で、ソフトウェア自体の商用ライセンスって道は存在しないのかも。

**Comment by shine-star** [comment]
MySQLはサーバーで使用した場合は頒布にあたらないからGPLの規約に影響しないので、
利用者がLilyの頒布が必須になる今回とは別に考えた方が良いと思いますよ。
（頒布の場合はGPLに違反し、サーバー側で使用はGPLに違反しないだったはず。）

＞そもそもパッチを商用利用しても問題ないのでは…？と気づいた。
1%のクローズなソースコードを合わせて、それをセットでライセンス販売すること自体は問題ないですよね。
他の人にもちょっとした改変物を優勝販売とかやられる可能性も十分にありますがｗ
まあ、そのようなことをやられそうになった場合でも、同様の機能をMITで公開してしまえば防げるとは思いますが。

**Comment by AknEp** [comment]
シャイんさんいつもありがとうござます。たしかにMySQLは事情が結構、違いますね。

> 1%のクローズなソースコードを合わせて、それをセットでライセンス販売すること自体は問題ないですよね。

そうなりますね。で、他の人もやれるし、僕もやれる。と。MITのライセンスの形式がよく分かってきました。

基本的な考え方としては、クラウドファンディング等で集めたお金（に相当する工数）で作った分は全てオープンなMITで公開する、それを足がかりにLilyを発展させるための営利活動をする場合はMITに基づいてエンジンを利用する事がある、って感じになりそうですね。

（余談ですが、WordPressもGPLで、商用のテーマやプラグインが存在してるの、限りなくクロに近いグレーっぽいです…ｗ）

**Comment by AknEp** [comment]
日付を置いてみたけれど、やはり今の考えかたで問題なさそうなのでクローズ。
