### ISSUE TITLE
プロトタイプ版の要件定義

### ISSUE THREAD

**Issue by AknEp** [AknEp/lily#8]
まずは、技術検証のためのプロトタイプ版を作ってみようと思うので、ざっと要件定義してみます。

### 振る舞い（いわゆる外部仕様？）

- 文字をアニメーション表示出来る
  - 自動改行
  - 自動ページ送り
- 禁則処理を考慮した文字表示（※ 禁則で詰められるケースで句点「。」が来てもガタつかない）
- レイヤに分けて画像を複数表示できる
- レイヤをアニメーション移動できる
- async/awaitなJSで文字、画像、アニメーションを記述できる
  - KAG風の文法からの変換は後回しで良いでしょ
- ごく簡単なセーブ＆ロード機構
  - 完全には動かなくても良いかもしれないが async/await のJSの任意箇所へのジャンプが出来るようにする必要がある

### 使う技術（いわゆる詳細仕様？）

- WebPack+Babel+ES2016
- PixiJS (原則としてWebGLのみサポート？)

### 留意事項

- あくまで仕様上の問題に気づく上でのプロトタイプ
- 音声まわりも厄介だけど、こっちとは独立してるので後回し
- アセットローダーっぽい部分もプロトでは雑に済ませる。推奨するディレクトリ構造もまだ検討できてないので、ざっくりKAGっぽく作る。

**Comment by shine-star** [comment]
ざっと見てみました。
contextって変数名ですが、canvas.getContext("2d")とこんがらがりそうなので別の名称がいいと思いました。
普通のCanvasモードは文字描画の際に使うことになるので、contextの変数名はそっちでも使うかと思います。

**Comment by shine-star** [comment]
あ、PIXI.jsの文字描画システムをそのまま使うなら避けられるかもしれません。
ただWebGLのテクスチャにはCanvasも利用可能なので、テクスチャのCanvasを生成する際にCanvasのcontextを弄る可能性はあるかもしれないということです。

**Comment by AknEp** [comment]
こちらですが、別で議論のあった「スクリプトも単一ソースにまとめるのではなく個別にロードしたい」件も含めて、ちょっと見直し中です！ レビューありがとうございます！

**Comment by AknEp** [comment]
「禁則処理を考慮した文字表示（※ 禁則で詰められるケースで句点「。」が来てもガタつかない）」 を追記。

以前cocos2d-xの禁則処理のコードを追った事があるんですが、
どうやらcocos2d-xでは、行に1文字ずつ足していって、普通に入れると文字が収まらないケースでも行末禁止文字の場合には足して、最後に必要なら行全体の字詰めを行う、というようなロジックでした。
今回も、おおむねそんな形になりそうです。
行末禁止文字が大量に羅列されている場合（※どんなだ…？ｗ）に一応備えて、行末禁止文字の繰り込みはN文字までにするとか、字詰めの限界値を決めるとか、するべきなんだと思います。
これ、Indesignとかだと、どうなってるんだろう…。

禁則情報はUnicode上で決まってるとかいう話もどこかで読んだので、正式版の時には追っておきたいです。

**Comment by shine-star** [comment]
お疲れ様です！
禁則文字はRPGとかですと適当に処理しがちですが、ノベルでは重要ですよね！
エンジンによって細かな事情が違って面白いです。

しかしES2016の仕様ガンガンに使っていますねｗ
Javascriptのclassの使い勝手はどうでしょうか？
私も以前使ったことがあるのですが、privateが使えないことに絶望した記憶があります。
あとstatic関数は使えたけどstatic変数の宣言方法が良く分からなかったので結局prototypeでの記述に戻してしまったりしました。

**Comment by AknEp** [comment]
特にツクールっぽい(≒スーファミっぽい？)RPGの場合は、1文字あたりの横幅が常に同一だった頃の名残があって、あんまり禁則は意識されないですよね。

classの使い勝手ですが、JSであることをあまり意識しなくて済んでるので楽ですね。
まだやってないんですが、1ファイル1クラスにしているので、 static variableが欲しい時は、クラスの外にletで定義すれば一緒かな、と思っています。 static function でgetter/setterを定義する必要があって、少し煩雑になりそうですが。

まだ概算で6時間くらいしか書いてないんですが、意識しなくてもthisをbindしてくれるアロー関数も含めて、JS特有の考え方を強いられる場面が少ないので、なんというか「普通に」書けばその通りに動作してくれるのが嬉しいですね。

ES2016の仕様をガンガン使ってみたのは、KAGっぽいスクリプトをそのままJSに変換する以上どのみちES2016仕様になるので、だったら遠慮せずに使っちゃおう、というのが1点と、
エンジンが普及するのにはどのみち年単位の時間がかかるので、その頃にはES2016やES2017をネイティブでサポートするブラウザも増えて来るんじゃないかなーという考えからですね。予測がはずれても現状既にbabelでちゃんと動いている、というのも嬉しいです。 （babelやbabylon等々を作った皆さんに感謝の念を送りながら）

また余談ですが、JSネイティブでは名前付き引数（っぽいオブジェクトへの代入記法）で引数をチェックする方法がないので、出来そうならジェネレータでチェックするつもりです。

**Comment by AknEp** [comment]
余談。 そういえば、一点だけES2016のclassでモヤっとした点があります。理解が浅くてやり方知らないだけかもなんですが、アロー関数のようにthisがbindされないので、ruby等のような（普通の）クラスベースオブジェクト指向っぽく扱っているつもりで、たまに「あれっ？」となりますね。

（呼ぶ時にbindする以外で良い方法知ってる人いたら教えてください…！）

**Comment by shine-star** [comment]
>JSネイティブでは名前付き引数（っぽいオブジェクトへの代入記法）で引数をチェックする方法

argumentsではなくてでしょうか？

JSを普通に触ってるとbind(this)が出るのは普通すぎて感覚が麻痺してしまいますねw
(私ならそのままbindしてしまう箇所です)

**Comment by AknEp** [comment]
名前付き引数っぽいやつでやりたいことなんですが

```
let hoge = function( {a, b="defaultB"} = {} ){
}
```

…みたいな関数定義の時に `hoge({c: "invalid param"})` としたときに、 cは受け付けてないよってチェックしてくれるものですねー。

欲しいのはタグ定義の部分だけなので、タグを定義する時にリフレクションとかで関数の中身を検査してやれば行けるかもです。 調べつつやってみますが、とりあえず後回しかも。

**Comment by AknEp** [comment]
気にして下さっている人も居るのでざっと共有（半分は自分向け）

ざっとお試し程度に画像表示や動かすロジックを試しているが、Pixiが優秀なのもあって、かなりサクサク進んでいる。

好ましくないかもと思っている点としては、
Engineがただのrendererのwrapperになっていて存在価値が不明瞭になっていること。
一応、本来の趣旨はレンダラをPixi以外のものにする事が出来る余地を残すことなので、やや非依存っぽい感じには実装しておきたい。

タグの定義については、ごく中心的なもの以外はdata以下に置いて好きにカスタマイズできる様にしたいので、後ほどシステムから完全分離を計る。
また、マクロ定義の時はタグを1から再定義してしまう方法の他に、Ruby界隈でよくつかうalias_method_chainに近い発想で使える、タグをラップするようなものも用意したい。
描画周りよりも、そっちの制御方式が固まっている事の方がシステム的には重要な気もする。

また、まだユーザーのタップ待ち等を入れてないので、そろそろ導入する。

文字描画にも取りかかりたい。禁則後回しにしても良いので、まずは文字が表示されることが大事。

立ち絵マクロ群は、デフォルトで動くプラグインっぽい感じでsystemフォルダに入れて初期ロードスクリプトに入れると動く、って感じにするとクールだと思う。

クロスフェードのアルゴリズムは予め入れておきたい。 ( https://dsp.stackexchange.com/questions/14754/equal-power-crossfade )
今のやり方で立ち絵が一瞬少しだけ透明になっちゃうのは、25%の透明度のオブジェクトと75%の透明度のオブジェクトを重ねてもアルファブレンディングの都合上100%にならないから（…だよね？）
（これ、某エンジンの標準立ち絵マクロでもそうなっちゃってて、Everett Effectの立ち絵が一瞬透明になるキモいバグの原因なので、ずっとどうにかしたいと思っている…個人的に因縁がある問題…）

**Comment by shine-star** [comment]
結構リツイートされてますね、ぜひとも頑張ってください！
>Engineがただのrendererのwrapperになっていて存在価値が不明瞭になっていること。
画像表示だけならその通りなのですが、他の処理も入れていけば価値が出てくると思いますよ！

>文字描画にも取りかかりたい。禁則後回しにしても良いので、まずは文字が表示されることが大事。
個人的には、禁則処理とかも初めからやっておいた方がいいと思います。
ここでやっておかないと、全部削除して一から処理を書き直すことになりますから・・・（経験談）。
ルビ、色を途中で変更、表示速度の調整、ブラウザ互換調整、キー入力チェック、フォントが正常に描画されているか、改行・・・。
たぶん文章表示だけで数週間～最悪１ケ月かかるんじゃないかなと予想しています。

ひたすらに地味な作業で報告しようにも理解して貰いづらい箇所かと思いますが、応援しています。

**Comment by AknEp** [comment]
ですね、最初はホントにやるか分かんないとか言ってましたが、ちょっと引き返せなくなってきました…ｗ

確かに、文字表示は魔窟ですね…。 でもノベルゲームの最重要要素だし、これは手がかかりそう…。
一旦、1日で出来る程度の簡易的なものをつくって、クラウドファンディング等に成功したらもっと凝る、みたいなメリハリがあっても良いのかもしれないです。
何にせよ、とても難易度が高そうなので、設計について深く考えておきます。 ありがとうございます！

**Comment by shine-star** [comment]
lily、名前的にエゴサしづらそうですが大丈夫でしょうか？
（名前自体の評価ではなくすみません）

>名前付き関数
JSではオブジェクト送ってるだけなので無いような気がします。
（このような記法が使える言語を知らないです・・・。


>ですね、最初はホントにやるか分かんないとか言ってましたが、ちょっと引き返せなくなってきました…ｗ

引き返すなら今のうちでしょうねｗ
これ以上進んだら戻れなそう・・・ｗ


しかしこれだけリツイートされるのは私も驚きました。
普通は出来上がってないゲームエンジンに興味を持たれることなど少ないと思います。
ノベルゲームエンジン自体も、HTML5以外を見れば大量にあるから尚更です。
それだけ求められているということなのかもしれませんね。



先ほど１ヵ月かかるかもと根拠無く書いてしまいましたが、
よく考えたら文章表示は縦書きとかもありましたね。
縦書き＋ルビ表示＋余白調整とかの手間も考えるともっとかかるかもしれませんね。
恐らく有用な縦書きライブラリは無いと思いますし。

あおみかんさんの言うとおり、
後で全部削除するのを承知で暫定的な措置をしてもいいかもしれませんね。

クラウドファンディング等が使えるなら考えてもいい頃合いなのかも？

**Comment by AknEp** [comment]
"lily engine" で検索してもらうつもりなので、まぁ大丈夫かなぁ、と。
もしかしたら正式版までに変えるかもしれませんが、今の所は気に入っているのでこの方向で行ってみます。

ルビはかなり高い需要があるのでやりたいですが、とりあえず暫定処置程度の実装はすすめてみようと思います。運良くこのままプロダクションコードにしても良さそうな気配が漂ってますが、
プロトの役割はPixi固有/JS固有/そもそも今考えているアーキテクチャの問題点を整理する事なので、
文字については全捨て覚悟で行ってみます。
ただ、間にタグが挟まっても表示できるような形にする必要はあるので、やはり、そこそこ大変そうですね。

色々と気遣って頂いて助かります！
あんまりスピードを落としたくないし、熱がある間に手を動かしまくりたいので、クラウドファンディングについても、本気で視野に入れたいですね。
私事ですが、実はちょうど案件の切れ目がすぐ先に見えていて、良いタイミングなんです。

**Comment by AknEp** [comment]
「ごく簡単なセーブ＆ロード機構」を目標に追加。 ksからJSに変換する機構との相性がイマイチ良くないので、どう辻褄合わせをするか検討したい。

`*label`形式のラベルはJSにもlabelがあるので何とかなる気がする。（ただ名前付きラベルは分離が必要な気もするので注意）

別解としては、if等の制御構文をtagsのメンバ関数に無名関数を投げる形式にするという手もある。(macroの定義と少し似ますね)
こっちの方がKAGとはアーキテクチャが近めになるかも。

**Comment by shine-star** [comment]
変数は普通にJSONで保存するとして、
KAG3はどのようなセーブ形式なのでしょう。
現在実行中の行をセーブするのでしょうかね？

ごり押しで行数を示すキー変数をを格納して、そこまでreturnで回すという手もありますがｗ

**Comment by shine-star** [comment]
Javascript:のラベル、forに対してしか使えないってなってるから使いづらそうですね。
（使ったことなかったです）
この方式だと指定行まで空ループする処理を来むしか無い気もしますね。
もしくはインタプリタか

**Comment by AknEp** [comment]
KAGParserのコードによると https://github.com/krkrz/KAGParser/blob/master/KAGParser.cpp#L1615  と周辺にあるように、一部のタグはパーサーの時点で処理されてるみたいです。

https://github.com/krkrz/KAGParser/blob/master/KAGParser.cpp#L1998 によると、PushCallStackが呼ばれ、 `tCallStackData(StorageName, labelname, CurLine - labelline,
		curline_content,
		LineBuffer, CurPos, LineBufferUsing, MacroArgStackBase, MacroArgStackDepth,
		ExcludeLevelStack, ExcludeLevel, IfLevelExecutedStack, IfLevel)` がpushされる模様。 ( https://github.com/krkrz/KAGParser/blob/master/KAGParser.cpp#L1301 )

何でパーサーの中でやってるの？ とかの疑問はありますが、多分パフォーマンスの都合と歴史的経緯でこうなっちゃってるんでしょう。

結局、知りたいのは、KAG3の栞にはcallstackやmacroの情報が保存されてるかどうかだったんですが、ちょっと、よく分かんなくなっちゃいましたね…。

とりあえず追ったログだけ残しておいて、プロトでは「ざっと」でやってみて、問題あれば再びKAGがどうなっているか追ってみたいと思います。

**Comment by shine-star** [comment]
結構複雑化してしまってるからあまり参考にしすぎずに書き直した方が良さそうですねｗ

＞FunctionオブジェクトのArray
なんか重くてやばくなりそうな気がしますｗ

保存方式、インタプリタ型にするかJS変換にするかで必要になるデータが変わってきますね。
インタプリタ型なら、｛マクロの開始位置、マクロの終了位置、行数、ループ処理情報の配列｝のコールスタックをそのまま保存すればいけると思いますが
JS型だとIF分岐の履歴などの情報も記録して実質既読スキップで元の位置まで戻るような処理をしないといけないから
ロードのコストが上がるかも？

**Comment by shine-star** [comment]
インタプリタ型にする場合でも、マクロの位置情報とかのみを抜き出したJSファイル、あるいはJSONファイルをあらかじめ生成するのはありかもしれませんね。
巨大ファイルのインタプリタを読み込む際、毎回マクロの行探索から入るのは若干非効率感がありますし。

**Comment by AknEp** [comment]
FunctionのArrayにするのはロードが重くてダメになっちゃいそうですよね。僕もそれを思ってやめにしましたｗ

スキップ処理は、インタプリタ型に対する明確なデメリットですね。
まぁ、if-else-endifなどをタグとして実装することで、

そういうわけで、インタプリタライクなJS型、という不思議アーキテクチャで一旦は進めてみます。
現状、既にsystem以下はBabelで弄ってFunctionオブジェクトを生成して実行しているわけなので（リリーサで前処理するっていうビジョンをあきらめれば）ロード時にはASTを弄るって手もありますね。（こっちも不思議アーキテクチャではありますが）

まぁ、JSでパーサーとインタプリタを書くよりはマシなんじゃないかなーと思うので、この方針で行ってみます。 1万行くらいあっても、すぐロードされると思います。

余談ですが、吉里吉里では栞にマクロを保持しててる気がしますが、これについてはmacrosディレクトリ以下とscenarioディレクトリ以下を明確に区別する、といった形で、ロード時にマクロの事を気にしなくて良い構造にしたいと思っています。
これに伴って、シナリオの途中にマクロ定義するのはLilyでは禁止するつもりです。 ドキュメントとエラーメッセージを分かりやすく整理すれば、初心者が混乱することもないはず。

**Comment by shine-star** [comment]
スタック情報の中に
type:"macro"またはtype:"subroutine"とかを１つ保存しておけばロード時の参照自体はいけるんじゃないかなと思いました。

＞シナリオの途中にマクロ定義するのはLilyでは禁止するつもりです。 
ksファイルからjsonファイルに変換するプログラムを用意する場合、
むしろシナリオの途中に記載されたマクロのみを抽出したmacro.jsonとかを作れるんじゃないですかね？
当然シナリオデータのjsonからはマクロ情報を削除して。

**Comment by shine-star** [comment]
あー、でもファイル分割ロードとかを考慮したらめんどくさくなりますね。

**Comment by AknEp** [comment]
マクロについて。
確かにその手はあるんですが、恐らく既存マクロをラップする処理などが今後出てくるので、その時に破綻しちゃうと思うんですよね。 分割ロードも含め。

そもそもソフトウェアの設計って難しいので、ある程度はCoCを徹底することで、初心者でも酷いアンチパターンを踏まずに済むと思うんですよねー。

**Comment by shine-star** [comment]
まあ、起動時にやたら時間がかかるような設計になってしまうと、
プレイヤーが嫌になって遊ぶのを止めてしまったりするので
高速に起動できるように注意を促す必要あるかもしれないですね。

**Comment by AknEp** [comment]
1万タグを超えるシナリオファイルをリリースしようとするとリリーサで警告をする/開発環境だと警告アラートが出るとか、そういうことしても良いかも。

インタプリタ形式でも、パーサーに負荷がかかるのでファイルは極端には長くしない方が良いという点では一緒ですねぇ。

**Comment by AknEp** [comment]
さっきのpushで禁則、セーブロード以外は、ざっくりですが実装できました！

セーブ＆ロード問題が片付いたら、if/else/endifくらいまでは実装して条件分岐の問題がないか確認して、いくつか目玉機能を実装しつつパフォーマンステストして、技術でもを仕上げて、クラウドファンディングの準備に入りたいと思います。
併せてライセンスの明記も必要ですね。 依存ライブラリのライセンスについても（出来ればpackage.jsonからの自動処理で）明記します。

また、後からまとめてやると地獄なので、クラウドファンディング準備と平行して、テストコードなど、足回り的な所に入りたいと思います。

**Comment by AknEp** [comment]
セーブデータのロード処理で使うつもりの「XXXラベルから数えてN番目のタグから実行」する機能を試してみました。おおむね目指す内容の通り動いていると思います。

if-elseの実装が一応出来ました。 ついでに簡易的なevalとsf/f/tf変数も使えるようにしてみました。

※ 内部のコールスタックはちゃんとやってないので、あくまでプロトタイプ実装です。タグが不完全な実装になっている場合の動作などがぜんぜん保証されません。

**Comment by AknEp** [comment]
手元のMacBook Pro (Retina, 13-inch, Mid 2014), 16GB, Chrome最新版にて、負荷テストを試してみました。 (proto-performance-testブランチ)

シナリオ先頭に1万行程度のタグ呼び出しを配置した上で、

どうやら、Babel.transformに20秒程度、 `debug` ラベルへのシーク処理に10秒程度かかっているみたいです。
（※Babelは500KB超えてるよって警告 ``[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB". を出してくれてます）

これは流石に重すぎますし、シナリオファイル1個を長いまとまりにしたい需要だってあるはずなので、対策を考える必要がありそうです。

### Babel.transformの事前実行

前々から課題だと感じてはいましたが、やはり Babel.transform を事前に実行する必要がありそうです。

### ks→js変換の時にJSを100タグ程度の単位に分解する

これは見出しの通りで、ksファイルからJSに変換する時にJSを分解することが出来るだろうと考えています。
どのファイルにどのlabelが含まれるか、何番目のマクロが含まれるかはksに対応するmanifestファイルを定義する事になると思います。

### 上記の半分インタプリタみたいな方式と完全なインタプリタ式の比較

これはあくまで感覚的なものですが、JSで完全なインタプリタを実装するとそれなりに重そうなので、限界ギリギリまで逃げてみたいと思ってます。

**Comment by shine-star** [comment]
ツクールなどもインタプリタですが、インタプリタで重い箇所はジャンプ時の移動探索かと思いますので
ks→JSON変換時に、ジャンプ後の行数をインタプリタ情報に含めてしまうのはどうでしょう？

[
{label:"if",exp:"f.money<f.price",jump:{endif:2}},
{label:"message","text":"お金が足りません"}
{label:"endif"}
]

ifのオブジェクトにjump:{endif:2}というのを追加して、2はendifの位置が[2]であることを示すというような感じで。

**Comment by AknEp** [comment]
あーなるほど！ 確かにその手もありますねー。

もし、よりインタプリタ式に寄せる必要が出てきたら、そっちの方針でトライしてみます！
ただ、今の方法はSourceMapするだけでブレークポイントを含むデバッガを起動できるなどのメリットがあるので、どうしようもなくなるまでは現行方式、ダメそうならJSONに切り替え、で行こうと思います！

**Comment by AknEp** [comment]
メモ: プロトでの今後のTODO

- [ ] 簡単なクリック待ち機能とタグ定義
- [ ] パーティクルなどPIXI.js側の機能でリッチな描画を試す（負荷テストも兼ねる）

**Comment by AknEp** [comment]
プロトとしては十分技術検証が出来たと思うのでこのIssueは終了しようと思います。

以後、僕側の都合もあるのですが、一応本当にゲームが作れるエンジンとしての「α版」に進もうと思います。 α1の段階では機能も不十分になると思いますが、これは設計最優先で。
